# Generated by Django 5.1 on 2024-08-20 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Championship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('temporada', models.CharField(max_length=20)),
                ('num_equipos', models.PositiveIntegerField()),
                ('fecha_inicio', models.DateField(blank=True)),
                ('fecha_fin', models.DateField(blank=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='championship_images/')),
            ],
            options={
                'verbose_name': 'Championship',
                'verbose_name_plural': 'Championships',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
