# Generated by Django 5.1 on 2024-08-21 21:43

import championship.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('championship', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='championship',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=championship.models.championship_image_path),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=30)),
                ('escudo', models.ImageField(upload_to=championship.models.team_image_path)),
                ('foto', models.ImageField(blank=True, null=True, upload_to=championship.models.team_image_path)),
                ('campeonato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='championship.championship')),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
                'ordering': ['nombre'],
            },
        ),
    ]
