# Generated by Django 5.1 on 2024-08-22 03:20

import championship.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('championship', '0002_alter_championship_imagen_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=10, unique=True)),
                ('dorsal', models.PositiveIntegerField(blank=True, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('fecha_nacimiento', models.DateField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to=championship.models.player_image_path)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('suspendido', 'Suspendido')], default='activo', max_length=10)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='championship.team')),
            ],
            options={
                'verbose_name': 'Player',
                'verbose_name_plural': 'Players',
                'ordering': ['nombre', 'apellido'],
            },
        ),
    ]
