# Generated by Django 5.1 on 2024-08-26 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('championship', '0003_player'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='equipo',
        ),
        migrations.CreateModel(
            name='PlayerTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('championship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_teams', to='championship.championship')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_teams', to='championship.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_teams', to='championship.team')),
            ],
            options={
                'verbose_name': 'Player Team',
                'verbose_name_plural': 'Player Teams',
                'unique_together': {('player', 'championship')},
            },
        ),
    ]
