# Generated by Django 5.1 on 2024-08-31 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('championship', '0006_alter_player_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='championship',
            name='categoria',
            field=models.CharField(choices=[('masculino', 'Masculino'), ('femenino', 'Femenino')], default='masculino', max_length=10),
        ),
        migrations.AddField(
            model_name='player',
            name='sexo',
            field=models.CharField(choices=[('masculino', 'Masculino'), ('femenino', 'Femenino')], default='masculino', max_length=10),
        ),
    ]
